In [9]:
import pickle


In [12]:
pickle.dump(b, open('test.p', 'w'))
c = pickle.load(open('test.p', 'rU'))
print c

[[3 4]
 [5 6]]


In [8]:
def test(hello, hi=2):
    print hello
    print hi
    
test('hello', **{'hi': 3})

TypeError: test() got an unexpected keyword argument 'i'

In [25]:
import pickle
pairs = pickle.load(open("test0.p", 'rU'))
print pairs

[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (0, 20), (0, 21), (0, 22), (0, 23), (0, 24), (0, 25), (0, 26), (0, 27), (0, 28), (0, 29), (0, 30), (0, 31), (0, 32), (0, 33), (0, 34), (0, 35), (0, 36), (0, 37), (0, 38), (0, 39), (0, 40), (0, 41), (0, 42), (0, 43), (0, 44), (0, 45), (0, 46), (0, 47), (0, 48), (0, 49), (0, 50), (0, 51), (0, 52), (0, 53), (0, 54), (0, 55), (0, 56), (0, 57), (0, 58), (0, 59), (0, 60), (0, 61), (0, 62), (0, 63), (0, 64), (0, 65), (0, 66), (0, 67), (0, 68), (0, 69), (0, 70), (0, 71), (0, 72), (0, 73), (0, 74), (0, 75), (0, 76), (0, 77), (0, 78), (0, 79), (0, 80), (0, 81), (0, 82), (0, 83), (0, 84), (0, 85), (0, 86), (0, 87), (0, 88), (0, 89), (0, 90), (0, 91), (0, 92), (0, 93), (0, 94), (0, 95), (0, 96), (0, 97), (0, 98), (1, 0), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), 

In [42]:
!python run_causal.py -d ../data/GeneExpressionData/test.txt -a granger_args.txt -t g -pl 2test0.p -o test0_granger

['t00_rep1', 't00_rep2plusextra', 't00_rep3plusextra', 't00_rep4']
['t05_rep1', 't05_rep2', 't05_rep3', 't05_rep4']
['t1_rep1', 't1_rep2', 't1_rep3', 't1_rep4']
['t2_rep1', 't2_rep2', 't2_rep3', 't2_rep4']
['t3_rep1', 't3_rep2', 't3_rep3', 't3_rep4']
['t4_rep1', 't4_rep2', 't4_rep3', 't4_rep4']
['t5_rep2', 't5_rep3', 't5_rep4']
['t6_rep2', 't6_rep3', 't6_rep4']
['t7_rep1', 't7_rep2', 't7_rep3', 't7_rep4']
['t8_rep1', 't8_rep2', 't8_rep3', 't8_rep4']
['t10_rep1', 't10_rep2', 't10_rep3', 't10_rep4']
['t12_rep1', 't12_rep2', 't12_rep3', 't12_rep4']
t00 has 4 data points
t05 has 4 data points
t1_ has 4 data points
t2_ has 4 data points
t3_ has 4 data points
t4_ has 4 data points
t5_ has 3 data points
t6_ has 3 data points
t7_ has 4 data points
t8_ has 4 data points
t10_ has 4 data points
t12_ has 4 data points
{'model_order': 3, 'use_processes': True, 'procnum': 32}
[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10)] [(0, 88), (0, 89), (0, 90), (0, 91), (0, 92

In [43]:
pickle.load(open('test0_granger', 'rU'))

(array([[ 1.        ,  0.03848786,  0.33747529, ...,  0.71818565,
          0.87600997,  0.        ],
        [ 0.        ,  1.        ,  0.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        , ...,  0.        ,
          0.        ,  0.        ],
        ..., 
        [ 0.        ,  0.        ,  0.        , ...,  1.        ,
          0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , ...,  0.        ,
          0.        ,  1.        ]]),
 array([[[ 0.        ,  0.        ,  0.        ],
         [ 0.22469827,  1.01623232,  0.14421371],
         [-0.04067299,  0.21928286,  0.12804095],
         ..., 
         [ 1.72102819,  4.48909597,  3.35513591],
         [-2.58981724, -1.22827197,  1.45926239],
         [ 0.        ,  0.        ,  0.        ]],
 
        [[ 0.        ,  0.        ,  0.        ],
    

In [1]:
!python prep_jobs.py -d ../data/GeneExpressionData/test.txt -a granger_args.txt -t g -plp 2test -o test0_granger -n 100

['t00_rep1', 't00_rep2plusextra', 't00_rep3plusextra', 't00_rep4']
['t05_rep1', 't05_rep2', 't05_rep3', 't05_rep4']
['t1_rep1', 't1_rep2', 't1_rep3', 't1_rep4']
['t2_rep1', 't2_rep2', 't2_rep3', 't2_rep4']
['t3_rep1', 't3_rep2', 't3_rep3', 't3_rep4']
['t4_rep1', 't4_rep2', 't4_rep3', 't4_rep4']
['t5_rep2', 't5_rep3', 't5_rep4']
['t6_rep2', 't6_rep3', 't6_rep4']
['t7_rep1', 't7_rep2', 't7_rep3', 't7_rep4']
['t8_rep1', 't8_rep2', 't8_rep3', 't8_rep4']
['t10_rep1', 't10_rep2', 't10_rep3', 't10_rep4']
['t12_rep1', 't12_rep2', 't12_rep3', 't12_rep4']
t00 has 4 data points
t05 has 4 data points
t1_ has 4 data points
t2_ has 4 data points
t3_ has 4 data points
t4_ has 4 data points
t5_ has 3 data points
t6_ has 3 data points
t7_ has 4 data points
t8_ has 4 data points
t10_ has 4 data points
t12_ has 4 data points
Pair lists written to 2test0.p
Script written to  test0_granger-script0.sh
Pair lists written to 2test1.p
Script written to  test0_granger-script1.sh
Pair lists written to 2test2.p
S

In [2]:
!ls -l

total 579864
-rw-r--r--   1 jlu96  staff          0 Jun  9 08:44 $
-rw-r--r--   1 jlu96  staff       1346 Jul  2 09:43 2test0.p
-rw-r--r--   1 jlu96  staff       1346 Jul  2 09:43 2test1.p
-rw-r--r--   1 jlu96  staff       1432 Jul  2 09:43 2test10.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test11.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test12.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test13.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test14.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test15.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test16.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test17.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test18.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test19.p
-rw-r--r--   1 jlu96  staff       1346 Jul  2 09:43 2test2.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test20.p
-rw-r--r--   1 jlu96  staff       1442 Jul  2 09:43 2test21.p
-rw-r-

In [53]:
!./test0_granger-script0.sh

['t00_rep1', 't00_rep2plusextra', 't00_rep3plusextra', 't00_rep4']
['t05_rep1', 't05_rep2', 't05_rep3', 't05_rep4']
['t1_rep1', 't1_rep2', 't1_rep3', 't1_rep4']
['t2_rep1', 't2_rep2', 't2_rep3', 't2_rep4']
['t3_rep1', 't3_rep2', 't3_rep3', 't3_rep4']
['t4_rep1', 't4_rep2', 't4_rep3', 't4_rep4']
['t5_rep2', 't5_rep3', 't5_rep4']
['t6_rep2', 't6_rep3', 't6_rep4']
['t7_rep1', 't7_rep2', 't7_rep3', 't7_rep4']
['t8_rep1', 't8_rep2', 't8_rep3', 't8_rep4']
['t10_rep1', 't10_rep2', 't10_rep3', 't10_rep4']
['t12_rep1', 't12_rep2', 't12_rep3', 't12_rep4']
t00 has 4 data points
t05 has 4 data points
t1_ has 4 data points
t2_ has 4 data points
t3_ has 4 data points
t4_ has 4 data points
t5_ has 3 data points
t6_ has 3 data points
t7_ has 4 data points
t8_ has 4 data points
t10_ has 4 data points
t12_ has 4 data points
{'model_order': 3, 'use_processes': True, 'procnum': 32}
[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10)] [(0, 88), (0, 89), (0, 90), (0, 91), (0, 92

In [4]:
import numpy as np
import pickle
import csv

filenames = []
for i in range(10):
    matr1 = np.zeros((10,10))
    matr1[i] = np.ones(10)
    
    matr2 = np.zeros((10,10))
    matr2[i] = -1 * np.ones(10)
    
    matr3 = 3 * matr2
    
    filename = "tuple"  + str(i) + ".p"
    pickle.dump((matr1, matr2, matr3), open(filename, 'w'))
    print "Written to ", filename
    filenames.append(filename)

with open("output_list.txt", 'w') as csvfile:
    writer = csv.writer(csvfile, delimiter='\t')
    for filename in filenames:
        writer.writerow([filename])

Written to  tuple0.p
Written to  tuple1.p
Written to  tuple2.p
Written to  tuple3.p
Written to  tuple4.p
Written to  tuple5.p
Written to  tuple6.p
Written to  tuple7.p
Written to  tuple8.p
Written to  tuple9.p


In [7]:
!python integrate_outputs.py -o "integrated.p"

Files to integrate are  ['tuple0.p', 'tuple1.p', 'tuple2.p', 'tuple3.p', 'tuple4.p', 'tuple5.p', 'tuple6.p', 'tuple7.p', 'tuple8.p', 'tuple9.p']
Integrated written to  integrated.p


In [10]:
pickle.load(open("integrated.p", 'rU'))

(array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]]),
 array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
        [-1., -1., -1., -1., -1., -1.,

In [23]:
!python prep_jobs.py -d ../data/GeneExpressionData/test.txt -a granger_args.txt -t g -o test_granger -n 10

['t00_rep1', 't00_rep2plusextra', 't00_rep3plusextra', 't00_rep4']
['t05_rep1', 't05_rep2', 't05_rep3', 't05_rep4']
['t1_rep1', 't1_rep2', 't1_rep3', 't1_rep4']
['t2_rep1', 't2_rep2', 't2_rep3', 't2_rep4']
['t3_rep1', 't3_rep2', 't3_rep3', 't3_rep4']
['t4_rep1', 't4_rep2', 't4_rep3', 't4_rep4']
['t5_rep2', 't5_rep3', 't5_rep4']
['t6_rep2', 't6_rep3', 't6_rep4']
['t7_rep1', 't7_rep2', 't7_rep3', 't7_rep4']
['t8_rep1', 't8_rep2', 't8_rep3', 't8_rep4']
['t10_rep1', 't10_rep2', 't10_rep3', 't10_rep4']
['t12_rep1', 't12_rep2', 't12_rep3', 't12_rep4']
t00 has 4 data points
t05 has 4 data points
t1_ has 4 data points
t2_ has 4 data points
t3_ has 4 data points
t4_ has 4 data points
t5_ has 3 data points
t6_ has 3 data points
t7_ has 4 data points
t8_ has 4 data points
t10_ has 4 data points
t12_ has 4 data points
Pair lists written to test_granger-pairs-0.p
Script written to  test_granger-script-0.sh
Pair lists written to test_granger-pairs-1.p
Script written to  test_granger-script-1.sh
Pair

In [24]:
!./run_all_no_cluster.sh

Submitting Script test_granger-script-0.sh
./test_granger-script-0.sh: line 2: module: command not found
./test_granger-script-0.sh: line 3: module: command not found
./test_granger-script-0.sh: line 4: module: command not found
./test_granger-script-0.sh: line 5: module: command not found
['t00_rep1', 't00_rep2plusextra', 't00_rep3plusextra', 't00_rep4']
['t05_rep1', 't05_rep2', 't05_rep3', 't05_rep4']
['t1_rep1', 't1_rep2', 't1_rep3', 't1_rep4']
['t2_rep1', 't2_rep2', 't2_rep3', 't2_rep4']
['t3_rep1', 't3_rep2', 't3_rep3', 't3_rep4']
['t4_rep1', 't4_rep2', 't4_rep3', 't4_rep4']
['t5_rep2', 't5_rep3', 't5_rep4']
['t6_rep2', 't6_rep3', 't6_rep4']
['t7_rep1', 't7_rep2', 't7_rep3', 't7_rep4']
['t8_rep1', 't8_rep2', 't8_rep3', 't8_rep4']
['t10_rep1', 't10_rep2', 't10_rep3', 't10_rep4']
['t12_rep1', 't12_rep2', 't12_rep3', 't12_rep4']
t00 has 4 data points
t05 has 4 data points
t1_ has 4 data points
t2_ has 4 data points
t3_ has 4 data points
t4_ has 4 data points
t5_ has 3 data points
t6_

In [25]:
!./integrate_outputs.sh

Files to integrate are  ['test_granger-0.p', 'test_granger-1.p', 'test_granger-2.p', 'test_granger-3.p', 'test_granger-4.p', 'test_granger-5.p', 'test_granger-6.p', 'test_granger-7.p', 'test_granger-8.p', 'test_granger-9.p']
Integrated written to  test_granger.p


In [31]:
b = pickle.load(open("test_granger.p", 'rU'))

In [33]:
c = pickle.load(open("della/test_granger/test_granger/test_granger.p", 'rU'))

In [34]:
b[0] - c[0]

array([[  0.00000000e+00,   0.00000000e+00,   2.22044605e-16, ...,
          1.11022302e-16,   0.00000000e+00,  -3.33066907e-16],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
         -4.44089210e-16,   1.11022302e-16,  -2.22044605e-16],
       [  0.00000000e+00,  -3.33066907e-16,   0.00000000e+00, ...,
          2.22044605e-16,   2.22044605e-16,  -2.22044605e-16],
       ..., 
       [ -4.44089210e-16,   1.11022302e-16,  -5.55111512e-16, ...,
          0.00000000e+00,   0.00000000e+00,   2.22044605e-16],
       [  1.11022302e-16,  -1.77635684e-15,   7.77156117e-16, ...,
         -2.22044605e-16,   0.00000000e+00,  -1.33226763e-15],
       [  1.11022302e-16,   0.00000000e+00,   4.44089210e-16, ...,
         -5.55111512e-16,  -4.44089210e-16,   0.00000000e+00]])

In [35]:
b[1] - c[1]

array([[[  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  3.88578059e-16,   1.99840144e-15,   5.05151476e-15],
        [  3.46944695e-17,   2.22044605e-16,  -2.22044605e-16],
        ..., 
        [  2.44249065e-15,   1.77635684e-15,   1.19904087e-14],
        [ -1.77635684e-15,  -3.77475828e-15,  -2.88657986e-15],
        [ -2.66453526e-15,  -3.37507799e-14,  -5.32907052e-15]],

       [[  1.22124533e-14,   4.44089210e-16,   1.77635684e-15],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        [  5.55111512e-17,   3.05311332e-16,   1.11022302e-15],
        ..., 
        [ -7.10542736e-15,  -2.30926389e-14,   9.23705556e-14],
        [  1.15463195e-14,   1.24344979e-14,  -7.10542736e-14],
        [ -2.39808173e-14,  -1.50990331e-14,  -1.11910481e-13]],

       [[ -1.77635684e-15,  -1.11022302e-15,  -4.44089210e-16],
        [  3.88578059e-16,   2.66453526e-15,   4.82947016e-15],
        [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
        